# Generated by Django 5.1.4 on 2025-02-10 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Overallprogress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_question', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance', to='entrance.entrance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='entrance.entrance')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_question', to='entrance.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
