# Generated by Django 5.1.4 on 2025-02-22 02:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0005_delete_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coursename', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='CourseDetails_image')),
                ('Logo', models.ImageField(upload_to='CourseDetails_logo')),
                ('Name', models.CharField(max_length=250)),
                ('About', ckeditor.fields.RichTextField(blank=True)),
                ('AdmissionGuidances', ckeditor.fields.RichTextField(blank=True)),
                ('Admissionlink', models.URLField()),
                ('clzlink', models.URLField()),
                ('Scholarship', ckeditor.fields.RichTextField(blank=True)),
                ('Location', models.CharField(max_length=250)),
                ('video_link', models.URLField(blank=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course_gallery/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='backwork.coursedetails')),
            ],
        ),
    ]
