# Generated by Django 5.1.4 on 2025-02-22 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0001_initial'),
        ('subjects', '0005_delete_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredprogram',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.course'),
        ),
    ]
