# Generated by Django 5.1.4 on 2025-02-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0002_offeredprogram_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='Address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
