# Generated by Django 5.1.4 on 2025-05-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0004_coursedetails_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseGallery',
        ),
    ]
