# Generated by Django 5.1.4 on 2025-01-23 19:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Image', models.ImageField(upload_to='Course_image')),
                ('Image2', models.ImageField(upload_to='Course_image')),
                ('Description', ckeditor.fields.RichTextField(blank=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Discount_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Real_price', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.district')),
                ('Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.field')),
                ('Uinversity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.university')),
            ],
        ),
    ]
