# Generated by Django 5.1.4 on 2025-02-07 03:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_course_discount_percent_remove_course_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Duration', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='Skill_image')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.level'),
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Field', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='Degree_image')),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.level')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Affiliation', models.CharField(max_length=250)),
                ('SchoolLevel', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='School_image')),
                ('Description', ckeditor.fields.RichTextField(blank=True)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.district')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.type')),
            ],
        ),
    ]
