# Generated by Django 5.1.4 on 2025-02-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_affiliation_schoollevel_skill_type_course_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, null=True)),
                ('Image', models.ImageField(null=True, upload_to='institute')),
                ('Location', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
