# Generated by Django 5.1.4 on 2025-02-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_institute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
